version: '3'

services:

  eventstore:
    image: eventstore/eventstore:release-5.0.3
    ports:
      - 2113:2113
      - 1113:1113
    volumes:
      - "~/Data/eventstorenode/node1:/var/lib/eventstore"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:2113/stats || exit 1"]
      interval: 5s
      timeout: 2s
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=all

  frontend:
    image: horfimbor/global_frontend:dev
    ports:
      - 80:80

  auth:
    image: horfimbor/service_auth:dev
    ports:
      - 8000:8000
    environment:
      - MOD_TOKEN_SECRET=example