version: '3'

services:

  eventstore:
    image: eventstore/eventstore:release-5.0.3
    ports:
      - 2113:2113
      - 1113:1113
    volumes:
      - "~/Data/eventstorenode/node1:/var/lib/eventstore"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:2113/stats || exit 1"]
      interval: 5s
      timeout: 2s
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=all
      - EVENTSTORE_EXT_IP=0.0.0.0
    networks:
      eventstore_net:
        ipv4_address: 172.28.1.1

  db:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
    networks:
      eventstore_net:
    volumes:
      - "~/Data/mariadb/node1:/var/lib/eventstore"

  db-admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      eventstore_net:

networks:
  eventstore_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16