version: '3'

services:

  frontend:
    image: horfimbor/global_frontend:dev
    ports:
      - 80:80
    networks:
      eventstore_net:

  auth:
    image: horfimbor/service_auth:dev
    ports:
      - 8000:8000
    environment:
      - MOD_TOKEN_SECRET=example
      - RUST_BACKTRACE=full
    networks:
      eventstore_net: