version: '3'

services:

  eventstore:
    image: eventstore/eventstore:release-5.0.3
    ports:
      - 2113:2113
      - 1113:1113
    volumes:
      - "~/Data/eventstorenode/node1:/var/lib/eventstore"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:2113/stats || exit 1"]
      interval: 5s
      timeout: 2s
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=all

  db:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
  # TODO add a volume

  db-admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080