version: '3'

services:

  frontend:
    image: horfimbor/global_frontend:dev
    ports:
      - 80:80
    networks:
      horfimbor_network:

  auth:
    image: horfimbor/service_auth:dev
    ports:
      - 8000:8000
    environment:
      - MOD_TOKEN_SECRET=example
      - RUST_BACKTRACE=full
    networks:
      horfimbor_network:

  stat:
    image: horfimbor/service_stat:dev
    ports:
      - 8001:8000
    environment:
      - RUST_BACKTRACE=full
    networks:
      horfimbor_network:

  asteroid_loot:
    image: horfimbor/service_asteroid_loot:dev
    ports:
      - 8002:8000
    environment:
      - RUST_BACKTRACE=full
      - MOD_SERVICE_SENTRY_DSN=http://8de1844f5c2c414dae0931f8254b1c07@sentry-base:9000/3
    networks:
      horfimbor_network:

  planet:
    image: horfimbor/service_planet:dev
    ports:
      - 8003:8000
    environment:
      - RUST_BACKTRACE=full
    networks:
      horfimbor_network: